name: silent_ledger
description: Silent Ledger - Smart Financial Management App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.2
  
  # UI & Styling
  sizer: ^2.0.15
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  
  # Data & Networking
  dio: ^5.7.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  
  # Charts & Visualization
  fl_chart: ^0.65.0
  
  # UI Feedback
  fluttertoast: ^8.2.4
  
  # Supabase Integration
  supabase_flutter: ^2.5.6
  
  # Sharing functionality for referral program
  share_plus: ^7.2.2

  # QR Code functionality
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

  web: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/